info:
  contact: {}
  license: {}
paths:
  /system/health:
    get:
      description: 描述信息
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 测试接口
      tags:
      - 系统管理
swagger: "2.0"
